flowchart TD
    Taskfile["Taskfile<br/>1 funcs"]
    examples__api_usage["examples.api-usage<br/>6 funcs"]
    examples__custom_hooks["examples.custom-hooks<br/>14 funcs"]
    examples__template_generator["examples.template-generator<br/>2 funcs"]
    examples__testing["examples.testing<br/>13 funcs"]
    examples__validation["examples.validation<br/>5 funcs"]
    examples__webhooks["examples.webhooks<br/>4 funcs"]
    goal__authors["goal.authors<br/>21 funcs"]
    goal__bootstrap["goal.bootstrap<br/>21 funcs"]
    goal__cli["goal.cli<br/>121 funcs"]
    goal__cli_helpers["goal.cli_helpers<br/>4 funcs"]
    goal__commit_generator["goal.commit_generator<br/>4 funcs"]
    goal__config["goal.config<br/>40 funcs"]
    goal__deep_analyzer["goal.deep_analyzer<br/>27 funcs"]
    goal__doctor["goal.doctor<br/>47 funcs"]
    goal__formatter["goal.formatter<br/>23 funcs"]
    goal__generator["goal.generator<br/>58 funcs"]
    goal__git_ops["goal.git_ops<br/>28 funcs"]
    goal__hooks["goal.hooks<br/>16 funcs"]
    goal__installers["goal.installers<br/>29 funcs"]
    goal__license["goal.license<br/>19 funcs"]
    goal__package_managers["goal.package_managers<br/>16 funcs"]
    goal__postcommit["goal.postcommit<br/>23 funcs"]
    goal__project_bootstrap["goal.project_bootstrap<br/>41 funcs"]
    goal__push["goal.push<br/>61 funcs"]
    goal__recovery["goal.recovery<br/>54 funcs"]
    goal__smart_commit["goal.smart_commit<br/>36 funcs"]
    goal__summary["goal.summary<br/>71 funcs"]
    goal__toml_validation["goal.toml_validation<br/>4 funcs"]
    goal__user_config["goal.user_config<br/>12 funcs"]
    goal__validation["goal.validation<br/>26 funcs"]
    goal__validators["goal.validators<br/>25 funcs"]
    goal__version_validation["goal.version_validation<br/>15 funcs"]
    project__map["project.map<br/>19290 funcs"]
    testql_scenarios__generated_from_pytests["testql-scenarios.generated-from-pytests<br/>2 funcs"]
    examples__api_usage ==>|102| Taskfile
    examples__testing ==>|59| Taskfile
    examples__custom_hooks ==>|50| Taskfile
    goal__push ==>|33| goal__git_ops
    goal__summary ==>|31| project__map
    examples__testing ==>|30| project__map
    examples__validation ==>|20| Taskfile
    goal__generator ==>|19| testql_scenarios__generated_from_pytests
    goal__cli ==>|19| goal__git_ops
    goal__push ==>|14| project__map
    goal__push ==>|14| goal__cli_helpers
    goal__cli ==>|13| goal__user_config
    goal__cli ==>|13| goal__config
    goal__cli ==>|12| project__map
    goal__deep_analyzer ==>|11| goal__user_config
    goal__project_bootstrap ==>|11| project__map
    examples__webhooks ==>|10| Taskfile
    goal__deep_analyzer ==>|10| testql_scenarios__generated_from_pytests
    goal__cli ==>|10| testql_scenarios__generated_from_pytests
    examples__template_generator ==>|9| Taskfile
    goal__validators ==>|9| goal__git_ops
    goal__summary ==>|9| testql_scenarios__generated_from_pytests
    goal__generator ==>|8| project__map
    goal__smart_commit ==>|8| testql_scenarios__generated_from_pytests
    examples__api_usage ==>|7| goal__git_ops
    goal__validators ==>|7| testql_scenarios__generated_from_pytests
    goal__validators ==>|7| project__map
    goal__push ==>|7| goal__cli
    goal__cli ==>|7| goal__license
    examples__custom_hooks ==>|6| project__map
    goal__deep_analyzer ==>|6| project__map
    goal__recovery ==>|6| testql_scenarios__generated_from_pytests
    goal__recovery ==>|6| project__map
    goal__summary ==>|6| goal__user_config
    examples__testing ==>|5| goal__project_bootstrap
    goal__git_ops ==>|5| project__map
    goal__push ==>|5| goal__formatter
    examples__api_usage ==>|4| goal__cli
    examples__testing ==>|4| goal__git_ops
    goal__commit_generator ==>|4| Taskfile
    goal__formatter ==>|4| project__map
    goal__generator ==>|4| goal__user_config
    goal__validators ==>|4| goal__user_config
    goal__cli ==>|4| goal__package_managers
    goal__cli ==>|4| goal__version_validation
    goal__doctor ==>|4| project__map
    examples__api_usage -->|3| goal__version_validation
    examples__api_usage -->|3| project__map
    examples__testing -->|3| goal__user_config
    goal__package_managers -->|3| project__map
    goal__push -->|3| examples__custom_hooks
    goal__cli -->|3| goal__authors
    goal__config -->|3| project__map
    goal__validation -->|3| project__map
    goal__doctor -->|3| goal__user_config
    goal__bootstrap -->|3| project__map
    goal__project_bootstrap -->|3| testql_scenarios__generated_from_pytests
    goal__user_config -->|2| project__map
    goal__package_managers -->|2| testql_scenarios__generated_from_pytests
    goal__hooks -->|2| project__map
    goal__installers -->|2| project__map
    goal__cli -->|2| goal__bootstrap
    goal__cli -->|2| goal__project_bootstrap
    goal__validation -->|2| goal__git_ops
    goal__smart_commit -->|2| project__map
    goal__authors -->|2| goal__user_config
    goal__license -->|2| project__map
    goal__license -->|2| testql_scenarios__generated_from_pytests
    goal__cli_helpers -->|2| goal__git_ops
    examples__custom_hooks -->|1| testql_scenarios__generated_from_pytests
    examples__api_usage -->|1| goal__config
    examples__api_usage -->|1| goal__user_config
    examples__api_usage -->|1| goal__doctor
    examples__api_usage -->|1| goal__generator
    examples__validation -->|1| project__map
    examples__template_generator -->|1| project__map
    examples__testing -->|1| goal__version_validation
    examples__testing -->|1| goal__push
    goal__cli -->|1| Taskfile
    goal__version_validation -->|1| testql_scenarios__generated_from_pytests
    goal__commit_generator -->|1| goal__generator
    goal__git_ops -->|1| testql_scenarios__generated_from_pytests
    goal__hooks -->|1| goal__git_ops
    goal__hooks -->|1| goal__validators
    goal__recovery -->|1| goal__user_config
    goal__push -->|1| goal__toml_validation
    goal__push -->|1| goal__bootstrap
    goal__push -->|1| goal__project_bootstrap
    goal__push -->|1| goal__validators
    goal__push -->|1| testql_scenarios__generated_from_pytests
    goal__cli -->|1| goal__formatter
    goal__cli -->|1| goal__toml_validation
    goal__cli -->|1| goal__push
    goal__postcommit -->|1| project__map
    goal__config -->|1| goal__user_config
    goal__smart_commit -->|1| goal__user_config
    goal__authors -->|1| goal__config
    goal__installers -->|1| testql_scenarios__generated_from_pytests
    goal__cli -->|1| goal__doctor
    goal__project_bootstrap -->|1| goal__doctor
    goal__bootstrap -->|1| goal__project_bootstrap
